### ISSUE TITLE
Inconsistent labelling

### ISSUE THREAD

**Issue by Efreak** [NextThingCo/CHIP-Hardware#7]
I was looking at the [silkscreening](https://github.com/NextThingCo/CHIP-Hardware/blob/master/CHIP%5Bv1_0%5D/CHIP_v1_0_ASSEMBLY_20151222.pdf) on CHIP to see which way to put the battery in. The [top](https://i1.someimage.com/4LNSwhD.png) of CHIP has a single `BAT` near the connector, as near to the edge as possible. The [bottom](https://i1.someimage.com/ZOvvLQX.png) of the chip shows a `BAT` closer to the middle of the chip, and a `GND` closer to the edge (I double-checked the physical CHIP, and it matches in these areas).

This confuses things for two reason--first, both pins seem to be labelled BAT, and secondly it would be much easier if the pins were simply labelled + and -. There is plenty of room for this on the bottom of the board. On the top (for those of us with the back-case on it and can't see the bottom...), there isn't as much room right next to the battery connector, but it was suggested to me that there could be a small diagram for the battery [between ANT1/C51 and R7](https://i1.someimage.com/9yco8SG.png). I'm guessing that the `BAT` on the top was intended simply to label the connector as a battery connector, but the polarity identification on the bottom uses a `BAT` that looks exactly the same.

**Comment by blinkengus** [comment]
The concern with labeling the top side of the PCB near J1 for + and - instead of BAT was that at first glance folks might think it was a copy of CHG-IN or a VCC rail. I believe this issue was more relevant for Kickstarter CHIPs where the back-side complete labels are obscured by the plastic case. It is, however on a punchlist to be revisited if we rev the CHIP PCB.
